FROM golang

LABEL maintainer="Melvin Kimathi"

COPY . /go/src/github.com/MelvinKim/wishlist

WORKDIR /go/src/github.com/MelvinKim/wishlist/auth

RUN go get github.com/prometheus/client_golang/prometheus
RUN go get github.com/prometheus/client_golang/prometheus/promhttp
RUN go get && go build -o /bin/auth

ENTRYPOINT ["/bin/auth"]