apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
  labels:
    app: wishlist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
      - name: wishlist
        image: melvinkimathi/auth-go:1.0
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: catalog
        image: melvinkimathi/catalog-go:1.0
        ports:
          - containerPort: 8081
        env:
          - name: PORT
            value: "8081"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: auth
        image: melvinkimathi/list-go:1.0
        ports:
          - containerPort: 8082
        env:
          - name: PORT
            value: "8082"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: wishlist
  ports:
  - name: wishlist-port
    protocol: TCP
    port: 8080
  - name: wishlist-auth-port
    protocol: TCP
    port: 8081
  - name: wishlist-catalog-port
    protocol: TCP
    port: 8082

